services:
  starter-kit:
    image: ghcr.io/gpickell/starter-kit/starter-kit:latest
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ca-certs:/usr/local/share/ca-certificates       
      - home:/home
      - config:/config

volumes:
  ca-certs: {}
  config: {}
  home: {}
