services:
  editor:
    build:
      context: starter-kit
    ports:
      - 127.0.0.1:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ca-certs:/usr/local/share/ca-certificates       
      - home:/home
      - config:/config
    environment:
      - PASSWORD=${ADMIN_INIT_SECRET:-}

volumes:
  ca-certs: {}
  config: {}
  home: {}
