services:
  starter-kit:
    build:
      context: ../starter-kit
    secrets:
      - admin-password
    ports:
      - 127.0.0.1:8080:8080

secrets:
  admin-password:
    external:
      name: vertigis-starter-kit-admin-password      
